"""initial schema

Revision ID: fad3544c0a82
Revises: 
Create Date: 2025-11-13 22:34:09.745996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fad3544c0a82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_state',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('last_successful_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider_sport_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('odds_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('conference', sa.String(length=32), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('bdl_team_id', sa.Integer(), nullable=True),
    sa.Column('nba_team_id', sa.String(length=32), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('provider_team_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bdl_team_id'),
    sa.UniqueConstraint('bdl_team_id', name='uq_teams_bdl_team_id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('canonical_name', name='uq_teams_canonical_name'),
    sa.UniqueConstraint('nba_team_id'),
    sa.UniqueConstraint('nba_team_id', name='uq_teams_nba_team_id')
    )
    op.create_table('games',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('season_type', sa.String(length=16), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('tipoff_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bdl_game_id', sa.Integer(), nullable=True),
    sa.Column('nba_game_id', sa.String(length=32), nullable=True),
    sa.Column('odds_api_event_id', sa.String(length=64), nullable=True),
    sa.Column('sgo_event_id', sa.String(length=64), nullable=True),
    sa.Column('provider_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bdl_game_id'),
    sa.UniqueConstraint('bdl_game_id', name='uq_games_bdl_game_id'),
    sa.UniqueConstraint('nba_game_id'),
    sa.UniqueConstraint('nba_game_id', name='uq_games_nba_game_id'),
    sa.UniqueConstraint('odds_api_event_id'),
    sa.UniqueConstraint('odds_api_event_id', name='uq_games_odds_event_id'),
    sa.UniqueConstraint('sgo_event_id'),
    sa.UniqueConstraint('sgo_event_id', name='uq_games_sgo_event_id')
    )
    op.create_index('ix_games_date_home_away', 'games', ['game_date', 'home_team_id', 'away_team_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('bdl_player_id', sa.Integer(), nullable=True),
    sa.Column('nba_player_id', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('height', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bdl_player_id'),
    sa.UniqueConstraint('bdl_player_id', name='uq_players_bdl_player_id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('nba_player_id'),
    sa.UniqueConstraint('nba_player_id', name='uq_players_nba_player_id')
    )
    op.create_table('game_odds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('bookmaker_key', sa.String(length=128), nullable=False),
    sa.Column('market_key', sa.String(length=128), nullable=False),
    sa.Column('line_type', sa.String(length=32), nullable=False),
    sa.Column('participant_type', sa.String(length=16), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.Column('participant_team_id', sa.Integer(), nullable=True),
    sa.Column('participant_player_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=32), nullable=True),
    sa.Column('line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('last_update_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(participant_type = 'team' AND participant_team_id IS NOT NULL AND participant_player_id IS NULL) OR (participant_type = 'player' AND participant_player_id IS NOT NULL AND participant_team_id IS NULL) OR (participant_type NOT IN ('team','player') AND participant_team_id IS NULL AND participant_player_id IS NULL)", name='ck_game_odds_participant'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['participant_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['participant_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'provider', 'bookmaker_key', 'market_key', 'participant_type', 'participant_name', 'side', 'line', 'snapshot_ts', name='uq_game_odds_snapshot')
    )
    op.create_table('odds_markets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('participant_type', sa.String(length=16), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=32), nullable=True),
    sa.Column('provider_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['odds_books.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'provider', 'bookmaker_id', 'market_type', 'participant_type', 'participant_id', 'side', 'line', 'as_of', name='uq_odds_markets_snapshot'),
    sa.UniqueConstraint('identity_key', name='uq_odds_markets_identity')
    )
    op.create_table('play_by_play',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_num', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock', sa.String(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player3_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player3_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'event_num', name='uq_pbp_game_event')
    )
    op.create_table('player_game_advanced',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('off_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('def_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('usage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ts_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('offensive_reb_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('defensive_reb_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assist_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steal_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('block_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game_adv_game_player')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(length=16), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('fg_attempts', sa.Integer(), nullable=True),
    sa.Column('fg_made', sa.Integer(), nullable=True),
    sa.Column('three_attempts', sa.Integer(), nullable=True),
    sa.Column('three_made', sa.Integer(), nullable=True),
    sa.Column('ft_attempts', sa.Integer(), nullable=True),
    sa.Column('ft_made', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game_stats_game_player')
    )
    op.create_table('checkpoints',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('worker', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('discovered','processing','done','error')", name='ck_checkpoint_status'),
    sa.PrimaryKeyConstraint('provider', 'date', 'provider_event_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_event_id', sa.Text(), nullable=False),
    sa.Column('sport_key', sa.Text(), nullable=True),
    sa.Column('commence_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('home_team', sa.String(length=255), nullable=True),
    sa.Column('away_team', sa.String(length=255), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_events_provider_event')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('markets', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('events_discovered', sa.Integer(), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('http_429_count', sa.Integer(), nullable=False),
    sa.Column('http_5xx_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('props_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('props',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('market_key', sa.Text(), nullable=False),
    sa.Column('line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bookmaker_key', sa.Text(), nullable=True),
    sa.Column('last_update_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_market_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['props_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', 'market_key', 'line', 'bookmaker_key', 'provider', name='uq_props_event_player_market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('props')
    op.drop_table('props_players')
    op.drop_table('ingestion_runs')
    op.drop_table('events')
    op.drop_table('checkpoints')
    op.drop_table('player_game_stats')
    op.drop_table('player_game_advanced')
    op.drop_table('play_by_play')
    op.drop_table('odds_markets')
    op.drop_table('game_odds')
    op.drop_table('players')
    op.drop_index('ix_games_date_home_away', table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('odds_books')
    op.drop_table('leagues')
    op.drop_table('ingestion_state')
    # ### end Alembic commands ###
